# =======================================================
# HYPRIDLE CONFIGURATION (Custom Timing)
# =======================================================

general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para invocar el candado
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de que el sistema entre en reposo
    after_sleep_cmd = hyprctl dispatch dpms on  # Asegurar que el monitor encienda al despertar
    
    # Gestión de periféricos (Drivers de tableta)
    on_lock_cmd = systemctl --user stop opentabletdriver
    on_unlock_cmd = systemctl --user start opentabletdriver
}

# 1. ATENUAR PANTALLA (A los 8 minutos - 480 segundos)
# Primer aviso visual de que la sesión está por bloquearse.
listener {
    timeout = 480                                
    on-timeout = brightnessctl set 10%          # Baja el brillo al 10%
    on-resume = brightnessctl set 100%          # Restaura el brillo al mover el mouse
}

# 2. BLOQUEAR SESIÓN (A los 12 minutos - 720 segundos)
# Asegura la sesión con tu hyprlock personalizado.
listener {
    timeout = 720                                
    on-timeout = loginctl lock-session           
}

# 3. APAGAR MONITOR (A los 15 minutos - 900 segundos)
# Ahorro de energía total después de haber bloqueado.
listener {
    timeout = 900                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 4. SUSPENSIÓN TOTAL (A los 20 minutos - 1200 segundos)
# El sistema entra en modo de bajo consumo (RAM).
listener {
    timeout = 1200                               
    on-timeout = systemctl suspend               
}
