-- =============================================================================
-- HYPRLAND MAIN CONFIGURATION
-- User: Efrain (Ckabos)
-- System: Arch Linux | Compositor: Hyprland
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. MODULARITY (Imports)
-- Separation of responsibilities for clean maintenance.
-- -----------------------------------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: $HOME/.config/hypr/conf/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.monitors")
-- Source: $HOME/.config/hypr/conf/environment.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.environment")
-- Source: $HOME/.config/hypr/conf/workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.workspaces")
-- Source: $HOME/.config/hypr/conf/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.keybinds")
-- Source: $HOME/.config/hypr/conf/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.input")
-- Source: $HOME/.config/hypr/conf/windowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.windowRules")
-- Source: $HOME/.config/hypr/conf/theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.theme")
-- Source: $HOME/.config/hypr/conf/layerRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.layerRules")

-- -----------------------------------------------------------------------------
-- 2. AUTO-START (Session Services)
-- -----------------------------------------------------------------------------

-- Initialization of the message bus and environment variables for Wayland/Systemd

-- Aesthetics and auditory feedback on startup
-- Sonido de inicio de sesión (The Legend of Zelda - BotW). Anterior: desktop-login.oga
-- exec-once=play $HOME/.config/hypr/assets/sounds/desktop-login.oga

-- Execute the text monitor
-- exec-once = wl-paste --type text --watch cliphist store 

-- Execute the image monitor
-- exec-once = wl-paste --type image --watch cliphist store

-- -----------------------------------------------------------------------------
-- 3. STARTUP APPLICATIONS (Via UWSM)
-- UWSM manages the life cycle of apps to improve stability.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- 4. SPECIFIC DEVICE CONFIGURATION
-- Hardware sensitivity adjustments.
-- -----------------------------------------------------------------------------
hl.device({
    name = "logitech-usb-receiver",
    sensitivity = -0.3,
})

hl.device({
    name = "e-signal-usb-gaming-mouse",
    sensitivity = -0.8,
})

-- -----------------------------------------------------------------------------
-- 5. GESTURES AND NAVIGATION
-- -----------------------------------------------------------------------------
hl.gesture({
    fingers = 3,
    direction = "vertical",
    action = "workspace",
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.curve("workspaceBez", { type = "bezier", points = { { 0.61, 1 }, { 0.88, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 15,
    bezier = "linear",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3,
    bezier = "workspaceBez",
    style = "slidevert",
})

hl.config({
    gestures = {
        workspace_swipe_invert = false,
    },
    general = {
        gaps_in = 2, -- Space between windows
        gaps_out = 1, -- Space between windows and monitor edge
        -- Tamaño del borde ajustado para resaltar el motion circular
        border_size = 4,
        layout = "dwindle", -- Organization algorithm (spiral)
        -- Los colores ahora son manejados dinámicamente por conf/theme.conf
    },
    cursor = {
        warp_on_change_workspace = true, -- Moves the cursor to the center when changing workspace
        no_warps = false,
    },
    group = {
        groupbar = {
            font_family = "JetBrainsMonoNerdFontMono-Regular",
            font_size = 10,
        },
    },
    -- -----------------------------------------------------------------------------
    -- 6. DECORATION AND AESTHETICS
    -- -----------------------------------------------------------------------------
    decoration = {
        rounding = 8,
        active_opacity = 1,
        inactive_opacity = 1,
        blur = {
            enabled = true,
            size = 10,
            passes = 5, -- Amount of passes for a smoother blur
            xray = false, -- If true, see through floating windows
        },
        shadow = {
            enabled = false,
        },
    },
    -- -----------------------------------------------------------------------------
    -- 7. ANIMATIONS
    -- -----------------------------------------------------------------------------
    animations = {
        enabled = true,
        -- Definition of custom Bezier curves
        -- Application of animations to elements
        -- VELOCIDAD REDUCIDA A 15: Ahora el bucle gira el doble de rápido
    },
    -- -----------------------------------------------------------------------------
    -- 8. SYSTEM BEHAVIOR (Misc)
    -- -----------------------------------------------------------------------------
    misc = {
        focus_on_activate = true, -- Gives focus to apps that request attention (e.g. an opened link)
        disable_hyprland_logo = true, -- Clears the background on startup
        disable_hyprland_guiutils_check = true,
        enable_anr_dialog = false, -- Disables "App not responding" dialog
        on_focus_under_fullscreen = 1, -- Keeps fullscreen mode when changing focus
    },
    -- Dwindle layout configuration (Inspired by BSPWM)
    dwindle = {
        -- pseudotile = yes                 # Allows windows with "fake" size (P)
        preserve_split = true, -- Maintains split direction when moving windows
    },
    -- Support for legacy X11 applications
    xwayland = {
        force_zero_scaling = true, -- Avoids blurriness in X11 apps with HiDPI
    },
    -- Hypr ecosystem notification configuration
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/home/efrain/Varda-Theme/themes/setCursor.sh")
    hl.exec_cmd("play /home/efrain/OkPanel/ags/sounds/zelda-botw-startup.mp3")
    hl.exec_cmd("uwsm app -- /home/efrain/.config/hypr/scripts/launchers/firefoxHomePageServer.sh")
    hl.exec_cmd("systemctl --user start okpanel.service")
    hl.exec_cmd("uwsm app -- udiskie -anT")
    hl.exec_cmd("uwsm app -- syncthing")
    hl.exec_cmd("uwsm app -- polkit-gnome-authentication-agent-1.desktop")
    hl.exec_cmd("uwsm app -- hypridle")
    -- Agente de bluetooth: empareja entrante (diálogos), notifica conexiones y
    -- ayuda a reconectar dispositivos de confianza. Sale en el tray de OkPanel.
    hl.exec_cmd("uwsm app -- blueman-applet")
end)

