-- ------------------------------
--  OkPanel — reglas de capa (blur)
-- ------------------------------
-- Los namespaces reales de este fork llevan el prefijo "okpanel-".
-- Hyprland 0.55 usa la sintaxis nueva de reglas:
--   layerrule = blur on, match:namespace ^(...)$
--   layerrule = ignore_alpha <umbral>, match:namespace ^(...)$
-- (La sintaxis clásica "blur, regex" da error en esta versión.)
-- El umbral ignore_alpha evita esmerilar las zonas totalmente
-- transparentes del marco; lo bajamos a 0.05 para que los temas
-- glass (alpha ~0.12) entren con holgura al esmerilado.

-- 1. Marco principal: barras + menús integrados (launcher, clipboard,
--    calendario, reverse shells, menú de sistema). Todo vive aquí.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.layer_rule({
    match = { namespace = "^(okpanel-frame)$" },
    blur = true,
    ignore_alpha = 0.05,
})

-- 2. Pop-ups de notificaciones
hl.layer_rule({
    match = { namespace = "^(okpanel-notifications)$" },
    blur = true,
    ignore_alpha = 0.05,
})

-- 3. Alertas (volumen, brillo)
hl.layer_rule({
    match = { namespace = "^(okpanel-alerts)$" },
    blur = true,
    ignore_alpha = 0.05,
})

