-- =========================================================
-- WINDOWRULES – Hyprland (SINTAXIS NUEVA)
-- =========================================================

-- ------------------------------
-- Polkit (autenticación)
-- ------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(polkit-gnome-authentication-agent-1)$",
    },
    float = true,
    stay_focused = true,
    no_anim = true,
    border_size = 0,
    decorate = false,
})

-- ------------------------------
-- Zathura
-- ------------------------------
hl.window_rule({
    match = {
        class = "^(org\\.pwmt\\.zathura)$",
    },
    opacity = "1.0 0.70",
})

-- ------------------------------
-- Calculadora GNOME
-- ------------------------------
hl.window_rule({
    match = {
        class = "^(org\\.gnome\\.Calculator|gnome-calculator)$",
    },
    float = true,
})

-- ------------------------------
-- Pulsemixer / nmtui / bluetuith
-- ------------------------------
hl.window_rule({
    match = {
        title = "^(pulsemixer|nmtui|bluetuith)$",
    },
    float = true,
    move = "1410 62",
    pin = true,
})

-- ------------------------------
-- Picture-in-Picture
-- ------------------------------
hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    move = "1492 839",
    size = "427 240",
    pin = true,
})

-- ------------------------------
-- Kitty floating y Clipse
-- ------------------------------
hl.window_rule({
    match = {
        class = "^(kitty-floating|clipse)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(clipse)$",
    },
    size = "652 652",
})

-- ------------------------------
-- Kooha (grabador de pantalla)
-- ------------------------------
hl.window_rule({
    match = {
        class = "^(io\\.github\\.seadve\\.Kooha)$",
    },
    float = true,
})

-- Regla para centrar la ventana
-- CORREGIDO: en el .conf faltaba la coma tras el matcher, así que no se aplicaban.
hl.window_rule({
    match = {
        class = "^(spotify-queue-window)$",
    },
    float = true,
    center = true,
    size = "400 200",
})

-- ==========================================
-- Smile Emoji Launcher Window Rules
-- ==========================================
hl.window_rule({
    match = {
        class = "^(it\\.mijorus\\.smile)$",
    },
    float = true,
    pin = true,
    center = true,
    size = "500 400",
    animation = "popin",
})

-- =========================================================
-- ASIGNACIÓN DE WORKSPACES
-- (sin silent = te lleva | con silent = no interrumpe)
-- =========================================================

-- W1 – Terminales (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(URxvt|Alacritty|kitty)$",
    },
    workspace = "1",
})

-- W2 – Navegadores (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(firefox|Opera|Brave-browser|brave-browser|Google-chrome|google-chrome|chromium|Chromium|floorp|librewolf|qutebrowser|org\\.qutebrowser\\.qutebrowser)$",
    },
    opacity = "0.90 0.90",
    workspace = "2",
})

-- W3 – Gestores de archivos (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(org\\.gnome\\.Nautilus|Nemo|Pcmanfm|pcmanfm|pcmanfm-qt|ranger|thunar|Thunar)$",
    },
    opacity = "0.90 0.90",
    workspace = "3",
})

-- W4 – Multimedia (SILENT)
hl.window_rule({
    match = {
        class = "^(Spotify|spotify|Spotube|mpv|Youtube|yuna|vlc|Vlc|celluloid|Celluloid)$",
    },
    opacity = "0.80 0.80",
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(qtws)$",
    },
    workspace = "4 silent",
    fullscreen = true,
})

-- W5 – IDEs / Dev (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(Code|code|code-oss|VSCodium|codium|Java|Eclipse|Apache\\ NetBeans\\ IDE\\ 12\\.4|wireshark|org\\.wireshark\\.Wireshark)$",
    },
    workspace = "5",
})

hl.window_rule({
    match = {
        class = "^(Java|Eclipse)$",
    },
    fullscreen = true,
})

-- W6 – Mensajería (SILENT)
hl.window_rule({
    match = {
        class = "^(discord|Discord|vesktop|org\\.telegram\\.desktop|Whatsapp-for-linux|Caprine|Signal|org\\.gabmus\\.giara|Wasistlos|whatsdesk)$",
    },
    opacity = "0.80 0.80",
    workspace = "6 silent",
})

-- W7 – Documentos / PDFs (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(Wpspdf|pdf|wps|et|wpp|Zathura|okular|obsidian|Bless|org\\.gnome\\.GHex|org\\.pwmt\\.zathura|net\\.code-industry\\.masterpdfeditor5|MasterPDFEditor)$",
    },
    workspace = "7",
})

-- W8 – Sistema / Utilidades (SILENT)
hl.window_rule({
    match = {
        class = "^(MEGAsync|Transmission-gtk|System-config-printer\\.py|obs|Protonvpn-gui|BlueMail|Alarm-clock-applet|Blueberry\\.py|Lxappearance|kdeconnect\\.app|kdeconnect-settings|kdeconnect-indicator|kdeconnect\\.sms|kdeconnect\\.daemon|Pavucontrol|Nitrogen|Flash_tool|Gnome-screenshot|copyq|arandr|org\\.pulseaudio\\.pavucontrol|blueman-manager|org\\.qbittorrent\\.qBittorrent|cheese|qbittorrent|Surfshark)$",
    },
    workspace = "8 silent",
})

hl.window_rule({
    match = {
        class = "^(MEGAsync|Transmission-gtk|System-config-printer\\.py|Protonvpn-gui|BlueMail|Gnome-screenshot|kdeconnect\\.daemon)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Surfshark)$",
    },
    fullscreen = true,
})

-- W8 – VM Windows 11 (visor SPICE) (TE LLEVA)
hl.window_rule({
    match = {
        class = "^([Ss]picy)$",
    },
    workspace = "8",
})

-- W9 – Reuniones (TE LLEVA)

-- Eliminamos la regla por title que tenías antes y usamos class para mayor precisión
hl.window_rule({
    match = {
        class = "^(teams-for-linux|zoom|gucharmap|Genymotion|ghidra-Ghidra|outlook-for-linux)$",
    },
    workspace = "9",
})

hl.window_rule({
    match = {
        class = "^(teams-for-linux|outlook-for-linux)$",
    },
    opacity = "0.85 0.85",
})

-- W10 – Juegos / Educación (TE LLEVA)
hl.window_rule({
    match = {
        class = "^(OpenBoard|EdrawMax|kolourpaint|Qalculate-gtk|GeoGebra|CrossCode|SkullGirls|Cyber\\ Shadow|pyrogenesis|ktouch|burp-StartBurp|jetbrains-studio|PacketTracer|org\\.wireshark\\.Wireshark|Postman|NecroDancer\\.x64|Caido|VirtualBox\\ Manager|scrcpy)$",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        class = "^(GeoGebra|CrossCode|SkullGirls|Cyber\\ Shadow|pyrogenesis)$",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        class = "^(scrcpy)$",
    },
    float = false,
    size = "445 988",
})

