-- --- GESTIÓN DE SESIÓN ---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
-- Asegura el backend correcto para input (mouse/teclado)
hl.env("LIBSEAT_BACKEND", "logind")

-- --- TOOLKITS (GTK, QT, SDL) ---
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")

-- --- CONFIGURACIÓN DE QT ---
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_SELECTION", "/usr/bin/qmake")

-- --- JAVA (CRÍTICO PARA PENTESTING) ---
-- Soluciona ventanas grises en Burp Suite, Ghidra y herramientas Java
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")

-- --- ELECTRON Y NAVEGADORES ---
-- CORREGIDO: en el .conf usaba = en vez de coma, así que no se aplicaba.
hl.env("ELECTRON_ARGS", "--enable-features=UseOzonePlatform --ozone-platform=wayland")
hl.env("NATIVE_WAYLAND", "1")
hl.env("OZONE_PLATFORM_HINT", "auto")
hl.env("MOZ_DBUS_REMOTE", "1")

-- --- APARIENCIA Y CURSOR ---
-- Ajustado para tu tema Miku
hl.env("XCURSOR_THEME", "miku-cursor-linux")
hl.env("XCURSOR_SIZE", "50")
hl.env("HYPRCURSOR_THEME", "miku-cursor-linux")
hl.env("HYPRCURSOR_SIZE", "50")

-- --- HARDWARE ---
-- Solo descomenta la siguiente línea si usas NVIDIA y el cursor desaparece.
-- Si tienes gráfica integrada o AMD, déjala comentada para mejor rendimiento.
-- env = WLR_NO_HARDWARE_CURSORS,1

hl.env("GTK_USE_PORTAL", "1")
hl.env("GDK_DEBUG", "portals")
hl.env("OLLAMA_MODELS", "/mnt/ssd/ollama")

