-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

-- Definir la ruta del panel (Actualizado para usar el binario global en tu $PATH)
local okpanel = "okpanel"

-- ======================
-- General
-- ======================
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + ALT + Q", hl.dsp.exit())
-- Reinicia OkPanel vía systemd (evita instancias huérfanas / bucle de reinicios)
hl.bind(mainMod .. " + ALT + R", hl.dsp.exec_cmd("systemctl --user restart okpanel.service"))

-- ======================
-- Bloqueo de Pantalla
-- ======================
hl.bind("CONTROL + ALT + Delete", hl.dsp.exec_cmd("hyprlock"))

-- ======================
-- Programas y Aplicaciones
-- ======================
-- bind = $mainMod, return, exec, uwsm app -- kitty --session fastfetch.session
hl.bind(mainMod .. " + return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + ALT + return", hl.dsp.exec_cmd("uwsm app -- kitty --session dashboard.session"))
hl.bind(mainMod .. " + ALT + y", hl.dsp.exec_cmd("uwsm app -- yazi-kitty.sh"))
hl.bind(mainMod .. " + ALT + b", hl.dsp.exec_cmd("uwsm app -- kitty -e btop"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus"))
-- Reverse Shell Generator de OkPanel (estilo revshells.com)
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("ags request -i OkPanel reverseShells"))
-- Wallpapers de OkPanel (locales + álbum remoto de Google Photos)
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("ags request -i OkPanel wallpapers"))
-- bind = $mainMod, period, exec, ags request -i OkPanel "emojis"
hl.bind("SUPER + period", hl.dsp.exec_cmd("smile"))
-- Mueve el workspace actual al SIGUIENTE monitor (relativo +1, con vuelta).
-- Genérico: no depende de nombres de monitor; Hyprland cicla por todos.
hl.bind(mainMod .. " + T", hl.dsp.workspace.move({ monitor = "+1" }))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("sh -c 'dest=\"$HOME/Imágenes/Screenshots/screenshot_$(date +%Y-%m-%d_%H-%M-%S).png\"; grim -g \"$(slurp)\" \"$dest\" && swappy -f \"$dest\" && wl-copy < \"$dest\"'"))

-- ======================
-- OkPanel (Menús y Widgets)
-- ======================
-- Launcher
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(okpanel .. " launcher"))
-- launcher (Atajo alternativo)
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd(okpanel .. " launcher"))
-- Programas
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(okpanel .. " menu"))
-- Calendario
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(okpanel .. " calendar"))
-- Portapapeles y Notificaciones
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(okpanel .. " clipboard"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(okpanel .. " notification"))
-- No molestar (silencia pop-ups y sonido de notificación).
-- Llama directo a la app: el cliente okpanel filtra comandos no listados.
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("ags request -i OkPanel dnd"))
-- Screenshots
hl.bind("print", hl.dsp.exec_cmd(okpanel .. " screenshot"))

-- ======================
-- Gestión de Ventanas
-- ======================
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))
-- bind = $mainMod, M, exec, uwsm stop,
hl.bind(mainMod .. " + M", hl.dsp.window.cycle_next({ next = true }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- ======================
-- 3. Foco y Movimiento (Direccional)
-- ======================
-- --- FLECHAS ---
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))

-- --- VIM KEYS (HJKL) ---
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

-- ======================
-- 4. Mover Ventanas (Swap)
-- ======================
-- --- FLECHAS ---
hl.bind(mainMod .. " + Left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + Right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + Up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + Down", hl.dsp.focus({ direction = "down" }))

-- --- VIM KEYS (HJKL) ---
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- ======================
-- 5. Redimensionar (Resize)
-- ======================
-- Usamos CONTROL para evitar conflictos con menús de apps
hl.bind(mainMod .. " + CONTROL + Left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + CONTROL + Right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + CONTROL + Up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + CONTROL + Down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Resize con Vim Keys
hl.bind(mainMod .. " + ALT + H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Ajuste fino (para ventanas flotantes)
hl.bind(mainMod .. " + ALT + Left", hl.dsp.window.move({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + Right", hl.dsp.window.move({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + Up", hl.dsp.window.move({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + ALT + Down", hl.dsp.window.move({ x = 0, y = 50, relative = true }))

-- ======================
-- Workspaces
-- ======================
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }), { dont_inhibit = true })
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }), { dont_inhibit = true })
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "previous" }), { dont_inhibit = true })

-- Escape de la VM (SPICE captura el teclado en pantalla completa):
-- Ctrl izq + Alt izq salta al workspace anterior aunque la app inhiba atajos (flag p)
hl.bind("CTRL + Alt_L", hl.dsp.focus({ workspace = "previous" }), { dont_inhibit = true })

-- Mover ventanas a workspaces
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }), { dont_inhibit = true })
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }), { dont_inhibit = true })

-- # Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "r+1" }))
-- bind = $mainMod, kp_down, workspace, r+1
-- bind = $mainMod, kp_up, workspace, r-1
-- bind = $mainMod, down, workspace, r+1
-- bind = $mainMod, up, workspace, r-1
-- bind = $mainMod, next, workspace, r+1
-- bind = $mainMod, prior, workspace, r-1
-- bind = , next, workspace, r+1
-- bind = , prior, workspace, r-1
-- bind = $mainMod, j, workspace, r+1
-- bind = $mainMod, k, workspace, r-1

-- ======================
-- Grupos y Mouse (Interacción)
-- ======================
-- Groups
-- bind = $mainMod, g, togglegroup
-- bind = $mainMod, Tab, changegroupactive
-- bind = $mainMod, l, lockactivegroup, toggle

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(mainMod .. " + ALT + mouse:272", hl.dsp.window.resize())

-- ======================
-- Volume and Media / Brightness
-- ======================
-- Se ha actualizado 'bindl' a 'bindel' en el volumen para permitir mantener presionada la tecla
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(okpanel .. " volume-up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(okpanel .. " volume-down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(okpanel .. " mute"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Brightness
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("/home/efrain/.config/hypr/scripts/brightness/changeBrightness.sh increase"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("/home/efrain/.config/hypr/scripts/brightness/changeBrightness.sh decrease"), { locked = true })

-- Tecla de calculadora: abre el launcher de OkPanel directo en modo "=" (cálculo).
-- Si tu tecla no dispara, ejecuta `wev` y cambia XF86Calculator por el keysym real.
hl.bind("XF86Calculator", hl.dsp.exec_cmd("ags request -i OkPanel calc"))
