-- See https://wiki.hyprland.org/Configuring/Monitors/

-- REGLA COMODÍN (fallback): cualquier monitor SIN regla específica se
-- auto-configura solo — resolución nativa (preferred), posición automática a
-- la derecha (auto) y escala automática según DPI (auto). Esto hace que
-- conectar 2, 3, 4 o N monitores desconocidos "simplemente funcione".
-- El output vacío ("") solo aplica cuando ninguna regla de abajo coincide,
-- así que NO pisa tus monitores específicos.
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

-- Home ultra wide
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:LG Electronics LG ULTRAGEAR+ 303NTRL72662",
    mode = "5120x1440@240",
    position = "0x0",
    scale = "1",
})

-- Drawing tablet
hl.monitor({
    output = "desc:UGD Artist 24 Pro 0x20200514",
    mode = "1920x1080@60",
    position = "5120x360",
    scale = "1",
})

-- Laptop
hl.monitor({
    output = "desc:BOE 0x0BCA",
    mode = "2256x1504@60",
    position = "0x0",
    scale = "1.3333",
})

-- Devi house office screen
hl.monitor({
    output = "desc:Dell Inc. DELL U3421WE 6JZ7753",
    mode = "3440x1440@75",
    position = "-3440x0",
    scale = "1",
})

-- Devi house other office screen
hl.monitor({
    output = "desc:Dell Inc. DELL U2723QE 4X2XK04",
    mode = "3840x2160@60",
    position = "-3840x0",
    scale = "1",
})

-- laptop dell
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.02",
    position = "0x0",
    scale = "1",
})

